name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:

  default-shell:

    strategy:

      fail-fast: false

      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - runs-on: ubuntu-latest
            config: -DBUILD_TESTS=1 -DBUILD_EXAMPLES=1
            prop: tests & examples
          - runs-on: macos-latest
            config: -DBUILD_TESTS=1 -DBUILD_EXAMPLES=0
            prop: tests
          - runs-on: windows-latest
            config: -DBUILD_TESTS=1 -DBUILD_EXAMPLES=0
            prop: tests

    defaults:
      run:
        shell: bash -l {0}

    name: "${{ matrix.runs-on }} • x64 ${{ matrix.args }}"
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      if: runner.os != 'Windows'
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv

    - name: Set conda environment
      if: runner.os == 'Windows'
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        environment-file: environment.yaml
        activate-environment: test
        auto-activate-base: false

    - name: Configure using CMake (!Windows)
      if: runner.os != 'Windows'
      run: cmake . ${{ matrix.config }}

    - name: Configure using CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        conda install -c conda-forge clang_win-64 ninja
        cmake . -G Ninja ${{ matrix.config }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Build C++ ${{ matrix.prop }}
      run: cmake --build .

    - name: Run C++ ${{ matrix.prop }}
      run: ctest --output-on-failure

    - name: Build and install Python module
      run: |
        python setup.py build
        python setup.py install

    - name: Run Python tests
      run: python ./test/Cartesian2d.py

    - name: Generate consistency data based on current commit
      if: runner.os == 'Linux'
      run: |
        python test/compare_versions/Cartesian2d_generate.py
        python test/compare_versions/Cartesian2d_check_main.py

    - name: Check consistency with v0.9.0
      if: runner.os == 'Linux'
      run: |
        conda install -c conda-forge python=3.8.5 python-gmatelastoplasticqpot=0.9.0
        python test/compare_versions/Cartesian2d_check_v0.6.3.py

    - name: Check consistency with v0.8.0
      if: runner.os == 'Linux'
      run: |
        conda install -c conda-forge python=3.8.5 python-gmatelastoplasticqpot=0.8.0
        python test/compare_versions/Cartesian2d_check_v0.6.3.py

    - name: Check consistency with v0.7.0
      if: runner.os == 'Linux'
      run: |
        conda install -c conda-forge python=3.8.5 python-gmatelastoplasticqpot=0.7.0
        python test/compare_versions/Cartesian2d_check_v0.6.3.py

    - name: Check consistency with v0.6.3
      if: runner.os == 'Linux'
      run: |
        conda install -c conda-forge python=3.8.5 python-gmatelastoplasticqpot=0.6.3
        python test/compare_versions/Cartesian2d_check_v0.6.3.py

    - name: Check consistency with v0.5.0
      if: runner.os == 'Linux'
      run: |
        conda install -c conda-forge python=3.8.5 python-gmatelastoplasticqpot=0.5.0
        python test/compare_versions/Cartesian2d_check_v0.5.0.py

    - name: Check consistency with v0.4.0
      if: runner.os == 'Linux'
      run: |
        conda install -c conda-forge python=3.8.5 python-gmatelastoplasticqpot=0.4.0
        python test/compare_versions/Cartesian2d_check_v0.2.2.py

    - name: Check consistency with v0.3.0
      if: runner.os == 'Linux'
      run: |
        conda install -c conda-forge python=3.8.5 python-gmatelastoplasticqpot=0.3.0
        python test/compare_versions/Cartesian2d_check_v0.2.2.py

    - name: Check consistency with v0.2.2
      if: runner.os == 'Linux'
      run: |
        conda install -c conda-forge python=3.8.5 python-gmatelastoplasticqpot=0.2.2
        python test/compare_versions/Cartesian2d_check_v0.2.2.py

